<a href="https://colab.research.google.com/github/rposhala/Principal-Component-Analysis-using-Python/blob/master/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#loading libraries
import numpy as np
import pandas as pd

Principal Component Analysis algorithm for dimension reduction

In [0]:
def PCAA(df,N):
  features = df.shape[1]
  df = df - df.mean(axis=0)
  cv_matrix = np.cov(df,rowvar=False)
  eigval,eigvec = np.linalg.eig(cv_matrix)
  reduced_dataset = np.matmul(df,np.delete(eigvec,np.argsort(eigval)[:features-N],axis = 1))
  return reduced_dataset

Loading a sample data set to test the PCA algorithm

In [0]:
# loading the data.csv file with our column names

data = pd.read_csv("data.csv", header = None , skiprows = 1)
dataframe = pd.DataFrame()
dataframe = pd.DataFrame(data)
df = np.asarray(dataframe)

implementing PCA on a dataset and checking the first two sample of reduced dataset

In [0]:
tn_pred = PCAA(df,5)
tn_pred[:2,:]

array([[-7.58465437,  0.26079567,  0.24801261, -0.62004918, -5.726554  ],
       [-8.7533318 , -0.05117531,  0.12007766,  4.04209553, -2.29942656]])

Checking the variances captured at different level of principal component inclusion

In [0]:
## we can check the variance captured at different level of principal component inclusion
for i in range(49):
  tn_pred = PCAA(df,i)
  # np.var(tn_pred,axis=0)
  print(np.sum(np.var(tn_pred,axis=0))/np.sum(np.var(df,axis=0)))

0.0
0.38851552435529374
0.61747975135955
0.7466745505900461
0.8375156896557148
0.9107084796004811
0.9715637696801569
0.9924005019446108
0.9943767061818128
0.9959724606267621
0.9974913198847445
0.9987501344087916
0.9999142881195372
0.9999511903389898
0.9999803451052298
0.999996735417726
0.9999990187486207
0.9999995860927057
0.9999998121475623
0.9999999229904082
0.9999999634095859
0.9999999875750003
0.9999999958944789
0.9999999983648182
0.999999999095869
0.9999999992227251
0.9999999993419836
0.9999999994534176
0.9999999995521299
0.999999999647821
0.999999999739659
0.9999999998104696
0.9999999998584728
0.999999999901661
0.9999999999427948
0.999999999970112
0.999999999976204
0.9999999999816965
0.9999999999864411
0.9999999999910364
0.9999999999948743
0.9999999999970611
0.9999999999990343
0.9999999999995492
0.9999999999998198
0.9999999999999908
0.9999999999999928
0.9999999999999941
0.9999999999999949


*********** The end ***

..

..

Rough Work generated while created an optimal code for PCA algorithm implementation

In [0]:
def PCAASVD(df,N):
  f = df.shape[1]
  # cv_matrix = np.cov(df,rowvar=False)
  u, s, v = np.linalg.svd(df, full_matrices=False,compute_uv=True)
  print(df.shape,u.shape,s.shape,v.shape)
  # red = np.zeros((features,features))
  # for i in range(N):
  # smat = np.zeros((f, f))
  # smat[:f, :f] 
  ld= np.diag(s)
  print(ld.shape)
  # a = np.matmul(u[:,:i],smat[:i,:i])
  a = np.matmul(u,ld)
  # print(a.shape)
  reduced_dataset = np.matmul(a,v)#[:i,:i])
  # reduced_dataset = np.matmul(df,red)
  return reduced_dataset

In [0]:
b = PCAASVD(df,4)
b,df

(40956, 49) (40956, 49) (49,) (49, 49)
(49, 49)


(array([[-3.01400000e-06, -4.41380000e-05, -2.77560000e-04, ...,
         -1.49850000e+00, -1.49840000e+00,  5.00000000e+00],
        [-4.53270000e-06, -2.72070000e-05,  1.15470000e-04, ...,
         -1.50480000e+00, -1.50490000e+00,  8.00000000e+00],
        [-9.61560000e-07,  1.52919999e-06, -6.37740000e-06, ...,
         -1.49750000e+00, -1.49750000e+00,  9.00000000e+00],
        ...,
        [-5.51160000e-06, -2.43520000e-05, -4.20350000e-04, ...,
         -1.49890000e+00, -1.49890000e+00,  8.00000000e+00],
        [-3.94340000e-06,  8.59599991e-07, -1.59090000e-05, ...,
         -1.49870000e+00, -1.49880000e+00,  1.10000000e+01],
        [-6.23450000e-06, -6.60210000e-05,  1.05720000e-04, ...,
         -1.49550000e+00, -1.49540000e+00,  9.00000000e+00]]),
 array([[-3.0140e-06, -4.4138e-05, -2.7756e-04, ..., -1.4985e+00,
         -1.4984e+00,  5.0000e+00],
        [-4.5327e-06, -2.7207e-05,  1.1547e-04, ..., -1.5048e+00,
         -1.5049e+00,  8.0000e+00],
        [-9.6156e-07,  1.

In [0]:
a = PCAA(df,4)
b = PCAASVD(df,4)
# np.allclose(a,b)
a.shape,b.shape

(40956, 49) (40956, 49) (49,) (49, 49)
(49, 49)


((40956, 4), (40956, 49))

In [0]:
cv = np.cov(df,rowvar=False)
eigval,eigvec = np.linalg.eig(cv)
print(df.shape)
# tn_pred = np.matmul(dataframe,np.delete(eigvec,np.argsort(eigval)[:48-6],axis = 1))
tn_pred = np.matmul(df,np.delete(eigvec,np.argsort(eigval)[:48-8],axis = 1))
# tst_pred = np.matmul(x_test_norm,np.delete(eigvec,np.argsort(eigval)[:48-21],axis = 1))
print(df.shape,tn_pred.shape)
# print(sk_x_train-tn_pred)
np.sum(np.var(tn_pred,axis=0))/np.sum(np.var(df,axis=0))

(40956, 48)
(40956, 48) (40956, 8)


0.9958773128480441

In [0]:
from sklearn.decomposition import PCA
# Make an instance of the Model
pca = PCA(0.9107)
pca.fit(df)
sk_x_train = pca.transform(df)
# sk_test_img = pca.transform(x_test_norm)
print(sk_x_train.shape)#,sk_test_img.shape)
sk_x_train[:2,:]

(40956, 5)


array([[-7.58465437,  0.26079567,  0.24801261,  0.62004918,  5.726554  ],
       [-8.7533318 , -0.05117531,  0.12007766, -4.04209553,  2.29942656]])

In [0]:
8# eigvec[np.argsort(eigval)[48-6:]]
# np.sum(eigval[np.argsort(eigval)[48-10:]])/np.sum(eigval)
# np.var(tn_pred)/np.var(df)
np.sum(np.var(tn_pred,axis=0))/np.sum(np.var(df,axis=0))

0.10208820357662275

In [0]:
a = [[1,2,1,4],[3,8,7,6],[7,9,2,8],[5,3,5,9]]
cv = np.cov(a,rowvar=False)
eigval,eigvec = np.linalg.eig(cv)
eigval,eigvec,np.delete(eigvec,[1],axis = 1)
s = np.matmul(a,np.delete(eigvec,np.argsort(eigval)[:2],axis = 1))
print(s,a)
print(eigval,eigvec,np.delete(eigvec,np.argsort(eigval)[:1],axis = 1))
print("*****")
smat = np.zeros((4, 4))
smat[:4, :4] = np.diag(eigval)
# a = np.matmul(u[:,:i],smat)
w = np.matmul(a,eigvec)
u = np.matmul(smat,w)
print(w,u)
np.sum(np.var(a,axis=0)),np.sum(np.var(np.matmul(a,eigvec),axis=0))
# np.argsort(eigval)[:1],eigval
# t = np.matrix.transpose(np.asarray(a))
# w = np.sum(t,axis = 1)/4
# r = t - w[:,np.newaxis]
# a = np.asarray([])
# a = np.outer(r[0],r[0]) + np.outer(r[1],r[1]) + np.outer(r[2],r[2])
# a/3,cv,r
# np.var(s)/np.var(a)

[[ -3.66902009   0.21153308]
 [-11.47523694  -4.15197901]
 [-13.54754959   2.30598141]
 [ -9.30744914  -0.5266946 ]] [[1, 2, 1, 4], [3, 8, 7, 6], [7, 9, 2, 8], [5, 3, 5, 9]]
[ 1.81072070e+01 -1.07899800e-15  7.23699374e+00  6.15579923e+00] [[-0.50565134 -0.67082039  0.45638791  0.29330324]
 [-0.73625054  0.2236068  -0.07980486 -0.63369261]
 [-0.27854129 -0.2236068  -0.86451567  0.35359215]
 [-0.35308159  0.67082039  0.19481764  0.62239816]] [[-0.50565134  0.45638791  0.29330324]
 [-0.73625054 -0.07980486 -0.63369261]
 [-0.27854129 -0.86451567  0.35359215]
 [-0.35308159  0.19481764  0.62239816]]
*****
[[ -3.66902009   2.23606798   0.21153308   1.86910281]
 [-11.47523694   2.23606798  -4.15197901   2.01990282]
 [-13.54754959   2.23606798   2.30598141   2.03625878]
 [ -9.30744914   2.23606798  -0.5266946    6.93498257]] [[-6.64357064e+01  4.04889458e+01  3.83027334e+00  3.38442316e+01]
 [ 1.23817577e-14 -2.41271288e-15  4.47997706e-15 -2.17947110e-15]
 [-9.80435316e+01  1.61824100e+01  1.

(23.625, 23.624999999999996)

In [0]:
# a = np.random.randn(9, 6)# + 1j*np.random.randn(9, 6)
a = np.asarray([[1,2,3,8],[9,3,8,5],[2,3,5,2]])
u, s, vh = np.linalg.svd(a, full_matrices=False)
# sm = np.zeros(:3,:3)
sm = np.diag(s)
print(s)
np.matmul(u,np.matmul(sm,vh))
np.matmul(sm[:2,:2],vh[])

# np.allclose(a, np.dot(u * s, vh)),
# u,s,vh,a,u.shape, s.shape, vh.shape, a.shape , u * s, np.dot(u * s, vh)

[16.02806424  5.91389304  2.66964901]


array([[-8.5323473 , -4.44955263, -9.71721916, -8.35912831],
       [ 3.27375232, -0.19815831,  1.29929291, -4.74649848],
       [-1.575308  ,  1.47044711,  1.37385946, -0.7718329 ]])

In [0]:
a.shape,u.shape,s.shape,vh.shape
# d = np.cov(a,rowvar=False)
# np.matmul(a,d)

((3, 4), (3, 3), (3,), (3, 4), array([[16.02806424,  0.        ,  0.        ],
        [ 0.        ,  5.91389304,  0.        ],
        [ 0.        ,  0.        ,  2.66964901]]))

In [0]:
smat = np.zeros((3, 3))
smat[:3, :3] = np.diag(s)
smat

array([[14.66839912,  0.        ,  0.        ],
       [ 0.        ,  2.09994751,  0.        ],
       [ 0.        ,  0.        ,  1.55829645]])

In [0]:
np.dot(u, np.dot(smat, vh)),np.dot(smat, vh)

(array([[1., 2., 3.],
        [3., 5., 2.],
        [9., 8., 5.]]), array([[-9.42410481, -9.56922007, -5.89730518],
        [ 1.30078326, -0.27982963, -1.62463467],
        [-0.70300176,  1.16263604, -0.76312107]]))

In [0]:
a = np.outer(u[:,1],vh[1,:])*s[1]
b = np.outer(u[:,0],vh[0,:])*s[0]
c = np.outer(u[:,2],vh[2,:])*s[2]
b+a

array([[0.84804011, 2.14184463, 3.13252744, 7.92554621],
       [8.41764   , 3.54359502, 8.50788848, 4.71466875],
       [3.4558023 , 1.64110366, 3.730364  , 2.71328027]])

In [0]:
a = [[1,2,1],[3,7,6],[9,2,8],[5,5,9]]
cv = np.cov(a,rowvar=False)
cv

array([[11.66666667, -2.        ,  9.33333333],
       [-2.        ,  6.        ,  3.        ],
       [ 9.33333333,  3.        , 12.66666667]])

In [0]:
cv = np.cov(np.transpose(a))#,rowvar=False)
cv

array([[11.66666667, -2.        ,  9.33333333],
       [-2.        ,  6.        ,  3.        ],
       [ 9.33333333,  3.        , 12.66666667]])